language: node_js
node_js:
  - "4.2"
before_script:
  - openssl req -x509 -newkey rsa:2048 -keyout test/key.pem -out test/cert.pem -days 7300 -nodes -subj '/CN=localhost'
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
